<a href="https://colab.research.google.com/github/sebastiancasas10/curso-ia-para-economia/blob/main/Taller_importaci%C3%B3n_y_extracci%C3%B3n_datos_Sebastian_Casas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

PUNTO 1

In [29]:
import numpy as np
import pandas as pd

In [30]:
# Que muestre todas las columnas
pd.options.display.max_columns = None
# En los dataframes, mostrar los float con dos decimales
pd.options.display.float_format = '{:,.2f}'.format

In [31]:
from google.colab import drive, files
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [32]:
path = '/content/drive/MyDrive/dataset_taller'

In [33]:
import os
os.chdir(path)

In [34]:
df_paises = pd.read_excel('dataset_paises.xlsx')

df_paises.head()

  DATASET,"SERIES_CODE","OBS_MEASURE","COUNTRY","NSDP_CAT","INDICATOR","TYPE_OF_TRANSFORMATION","FREQUENCY","SCALE","DECIMALS_DISPLAYED","NSDP_IND","PRICES","S_ADJUSTMENT","TRANSFORMATION","UNIT","GENDER","DOI","FULL_DESCRIPTION","AUTHOR","PUBLISHER","DEPARTMENT","CONTACT_POINT","CREATOR","DATA_OWNER","DATA_STEWARD","TOPIC","TOPIC_DATASET","KEYWORDS","KEYWORDS_DATASET","LANGUAGE","PUBLICATION_DATE","UPDATE_DATE","METHODOLOGY","METHODOLOGY_NOTES","ACCESS_SHARING_LEVEL","ACCESS_SHARING_NOTES","SECURITY_CLASSIFICATION","SOURCE","SHORT_SOURCE_CITATION","FULL_SOURCE_CITATION","LICENSE","SUGGESTED_CITATION","KEY_INDICATOR","SERIES_NAME","1914","1914-Q1","1914-M01","1914-M02","1914-M03","1914-Q2","1914-M04","1914-M05","1914-M06","1914-Q3","1914-M07","1914-M08","1914-M09","1914-Q4","1914-M10","1914-M11","1914-M12","1915","1915-Q1","1915-M01","1915-M02","1915-M03","1915-Q2","1915-M04","1915-M05","1915-M06","1915-Q3","1915-M07","1915-M08","1915-M09","1915-Q4","1915-M10","1915-M11","1915-M12","1916","1916-Q1","1916-M01","1916-M02","1916-M03","1916-Q2","1916-M04","1916-M05","1916-M06","1916-Q3","1916-M07","1916-M08","1916-M09","1916-Q4","1916-M10","1916-M11","1916-M12","1917","1917-Q1","1917-M01","1917-M02","1917-M03","1917-Q2","1917-M04","1917-M05","1917-M06","1917-Q3","1917-M07","1917-M08","1917-M09","1917-Q4","1917-M10","1917-M11","1917-M12","1918","1918-Q1","1918-M01","1918-M02","1918-M03","1918-Q2","1918-M04","1918-M05","1918-M06","1918-Q3","1918-M07","1918-M08","1918-M09","1918-Q4","1918-M10","1918-M11","1918-M12","1919","1919-Q1","1919-M01","1919-M02","1919-M03","1919-Q2","1919-M04","1919-M05","1919-M06","1919-Q3","1919-M07","1919-M08","1919-M09","1919-Q4","1919-M10","1919-M11","1919-M12","1920","1920-Q1","1920-M01","1920-M02","1920-M03","1920-Q2","1920-M04","1920-M05","1920-M06","1920-Q3","1920-M07","1920-M08","1920-M09","1920-Q4","1920-M10","1920-M11","1920-M12","1921","1921-Q1","1921-M01","1921-M02","1921-M03","1921-Q2","1921-M04","1921-M05","1921-M06","1921-Q3","1921-M07","1921-M08","1921-M09","1921-Q4","1921-M10","1921-M11","1921-M12","1922","1922-Q1","1922-M01","1922-M02","1922-M03","1922-Q2","1922-M04","1922-M05","1922-M06","1922-Q3","1922-M07","1922-M08","1922-M09","1922-Q4","1922-M10","1922-M11","1922-M12","1923","1923-Q1","1923-M01","1923-M02","1923-M03","1923-Q2","1923-M04","1923-M05","1923-M06","1923-Q3","1923-M07","1923-M08","1923-M09","1923-Q4","1923-M10","1923-M11","1923-M12","1924","1924-Q1","1924-M01","1924-M02","1924-M03","1924-Q2","1924-M04","1924-M05","1924-M06","1924-Q3","1924-M07","1924-M08","1924-M09","1924-Q4","1924-M10","1924-M11","1924-M12","1925","1925-Q1","1925-M01","1925-M02","1925-M03","1925-Q2","1925-M04","1925-M05","1925-M06","1925-Q3","1925-M07","1925-M08","1925-M09","1925-Q4","1925-M10","1925-M11","1925-M12","1926","1926-Q1","1926-M01","1926-M02","1926-M03","1926-Q2","1926-M04","1926-M05","1926-M06","1926-Q3","1926-M07","1926-M08","1926-M09","1926-Q4","1926-M10","1926-M11","1926-M12","1927","1927-Q1","1927-M01","1927-M02","1927-M03","1927-Q2","1927-M04","1927-M05","1927-M06","1927-Q3","1927-M07","1927-M08","1927-M09","1927-Q4","1927-M10","1927-M11","1927-M12","1928","1928-Q1","1928-M01","1928-M02","1928-M03","1928-Q2","1928-M04","1928-M05","1928-M06","1928-Q3","1928-M07","1928-M08","1928-M09","1928-Q4","1928-M10","1928-M11","1928-M12","1929","1929-Q1","1929-M01","1929-M02","1929-M03","1929-Q2","1929-M04","1929-M05","1929-M06","1929-Q3","1929-M07","1929-M08","1929-M09","1929-Q4","1929-M10","1929-M11","1929-M12","1930","1930-Q1","1930-M01","1930-M02","1930-M03","1930-Q2","1930-M04","1930-M05","1930-M06","1930-Q3","1930-M07","1930-M08","1930-M09","1930-Q4","1930-M10","1930-M11","1930-M12","1931","1931-Q1","1931-M01","1931-M02","1931-M03","1931-Q2","1931-M04","1931-M05","1931-M06","1931-Q3","1931-M07","1931-M08","1931-M09","1931-Q4","1931-M10","1931-M11","1931-M12","1932","1932-Q1","1932-M01","1932-M02","1932-M03","1932-Q2","1932-M04","1932-M05","1932-M06","1932-Q3","1932-M07","1932-M08","1932-M09","1932-Q4","1932-M10","1932-M11","1932-M12","1933","1933-Q1","1933-M01","1933-M02","1933-M03","1933-Q2","1933-M04","1933-M05","1933-M06","1933-Q3","1933-M07","1933-M08","1933-M09","1933-Q4","1933-M10","1933-M11","1933-M12","1934","1934-Q1","1934-M01","1934-M02","1934-M03","1934-Q2","1934-M04","1934-M05","1934-M06","1934-Q3","1934-M07","1934-M08","1934-M09","1934-Q4","1934-M10","1934-M11","1934-M12","1935","1935-Q1","1935-M01","1935-M02","1935-M03","1935-Q2","1935-M04","1935-M05","1935-M06","1935-Q3","1935-M07","1935-M08","1935-M09","1935-Q4","1935-M10","1935-M11","1935-M12","1936","1936-Q1","1936-M01","1936-M02","1936-M03","1936-Q2","1936-M04","1936-M05","1936-M06","1936-Q3","1936-M07","1936-M08","1936-M09","1936-Q4","1936-M10","1936-M11","1936-M12","1937","1937-Q1","1937-M01","1937-M02","1937-M03","1937-Q2","1937-M04","1937-M05","1937-M06","1937-Q3","1937-M07","1937-M08","1937-M09","1937-Q4","1937-M10","1937-M11","1937-M12","1938","1938-Q1","1938-M01","1938-M02","1938-M03","1938-Q2","1938-M04","1938-M05","1938-M06","1938-Q3","1938-M07","1938-M08","1938-M09","1938-Q4","1938-M10","1938-M11","1938-M12","1939","1939-Q1","1939-M01","1939-M02","1939-M03","1939-Q2","1939-M04","1939-M05","1939-M06","1939-Q3","1939-M07","1939-M08","1939-M09","1939-Q4","1939-M10","1939-M11","1939-M12","1940","1940-Q1","1940-M01","1940-M02","1940-M03","1940-Q2","1940-M04","1940-M05","1940-M06","1940-Q3","1940-M07","1940-M08","1940-M09","1940-Q4","1940-M10","1940-M11","1940-M12","1941","1941-Q1","1941-M01","1941-M02","1941-M03","1941-Q2","1941-M04","1941-M05","1941-M06","1941-Q3","1941-M07","1941-M08","1941-M09","1941-Q4","1941-M10","1941-M11","1941-M12","1942","1942-Q1","1942-M01","1942-M02","1942-M03","1942-Q2","1942-M04","1942-M05","1942-M06","1942-Q3","1942-M07","1942-M08","1942-M09","1942-Q4","1942-M10","1942-M11","1942-M12","1943","1943-Q1","1943-M01","1943-M02","1943-M03","1943-Q2","1943-M04","1943-M05","1943-M06","1943-Q3","1943-M07","1943-M08","1943-M09","1943-Q4","1943-M10","1943-M11","1943-M12","1944","1944-Q1","1944-M01","1944-M02","1944-M03","1944-Q2","1944-M04","1944-M05","1944-M06","1944-Q3","1944-M07","1944-M08","1944-M09","1944-Q4","1944-M10","1944-M11","1944-M12","1945","1945-Q1","1945-M01","1945-M02","1945-M03","1945-Q2","1945-M04","1945-M05","1945-M06","1945-Q3","1945-M07","1945-M08","1945-M09","1945-Q4","1945-M10","1945-M11","1945-M12","1946","1946-Q1","1946-M01","1946-M02","1946-M03","1946-Q2","1946-M04","1946-M05","1946-M06","1946-Q3","1946-M07","1946-M08","1946-M09","1946-Q4","1946-M10","1946-M11","1946-M12","1947","1947-Q1","1947-M01","1947-M02","1947-M03","1947-Q2","1947-M04","1947-M05","1947-M06","1947-Q3","1947-M07","1947-M08","1947-M09","1947-Q4","1947-M10","1947-M11","1947-M12","1948","1948-Q1","1948-M01","1948-M02","1948-M03","1948-Q2","1948-M04","1948-M05","1948-M06","1948-Q3","1948-M07","1948-M08","1948-M09","1948-Q4","1948-M10","1948-M11","1948-M12","1949","1949-Q1","1949-M01","1949-M02","1949-M03","1949-Q2","1949-M04","1949-M05","1949-M06","1949-Q3","1949-M07","1949-M08","1949-M09","1949-Q4","1949-M10","1949-M11","1949-M12","1950","1950-Q1","1950-M01","1950-M02","1950-M03","1950-Q2","1950-M04","1950-M05","1950-M06","1950-Q3","1950-M07","1950-M08","1950-M09","1950-Q4","1950-M10","1950-M11","1950-M12","1951","1951-Q1","1951-M01","1951-M02","1951-M03","1951-Q2","1951-M04","1951-M05","1951-M06","1951-Q3","1951-M07","1951-M08","1951-M09","1951-Q4","1951-M10","1951-M11","1951-M12","1952","1952-Q1","1952-M01","1952-M02","1952-M03","1952-Q2","1952-M04","1952-M05","1952-M06","1952-Q3","1952-M07","1952-M08","1952-M09","1952-Q4","1952-M10","1952-M11","1952-M12","1953","1953-Q1","1953-M01","1953-M02","1953-M03","1953-Q2","1953-M04","1953-M05","1953-M06","1953-Q3","1953-M07","1953-M08","1953-M09","1953-Q4","1953-M10","1953-M11","1953-M12","1954","1954-Q1","1954-M01","1954-M02","1954-M03","1954-Q2","1954-M04","1954-M05","1954-M06","1954-Q3","1954-M07","1954-M08","1954-M09","1954-Q4","1954-M10","1954-M11","1954-M12","1955","1955-Q1","1955-M01","1955-M02","1955-M03","1955-Q2","1955-M04","1955-M05","1955-M06","1955-Q3","1955-M07","1955-M08","1955-M09","1955-Q4","1955-M10","1955-M11","1955-M12","1956","1956-Q1","1956-M01","1956-M02","1956-M03","1956-Q2","1956-M04","1956-M05","1956-M06","1956-Q3","1956-M07","1956-M08","1956-M09","1956-Q4","1956-M10","1956-M11","1956-M12","1957","1957-Q1","1957-M01","1957-M02","1957-M03","1957-Q2","1957-M04","1957-M05","1957-M06","1957-Q3","1957-M07","1957-M08","1957-M09","1957-Q4","1957-M10","1957-M11","1957-M12","1958","1958-Q1","1958-M01","1958-M02","1958-M03","1958-Q2","1958-M04","1958-M05","1958-M06","1958-Q3","1958-M07","1958-M08","1958-M09","1958-Q4","1958-M10","1958-M11","1958-M12","1959","1959-Q1","1959-M01","1959-M02","1959-M03","1959-Q2","1959-M04","1959-M05","1959-M06","1959-Q3","1959-M07","1959-M08","1959-M09","1959-Q4","1959-M10","1959-M11","1959-M12","1960","1960-Q1","1960-M01","1960-M02","1960-M03","1960-Q2","1960-M04","1960-M05","1960-M06","1960-Q3","1960-M07","1960-M08","1960-M09","1960-Q4","1960-M10","1960-M11","1960-M12","1961","1961-Q1","1961-M01","1961-M02","1961-M03","1961-Q2","1961-M04","1961-M05","1961-M06","1961-Q3","1961-M07","1961-M08","1961-M09","1961-Q4","1961-M10","1961-M11","1961-M12","1962","1962-Q1","1962-M01","1962-M02","1962-M03","1962-Q2","1962-M04","1962-M05","1962-M06","1962-Q3","1962-M07","1962-M08","1962-M09","1962-Q4","1962-M10","1962-M11","1962-M12","1963","1963-Q1","1963-M01","1963-M02","1963-M03","1963-Q2","1963-M04","1963-M05","1963-M06","1963-Q3","1963-M07","1963-M08","1963-M09","1963-Q4","1963-M10","1963-M11","1963-M12","1964","1964-Q1","1964-M01","1964-M02","1964-M03","1964-Q2","1964-M04","1964-M05","1964-M06","1964-Q3","1964-M07","1964-M08","1964-M09","1964-Q4","1964-M10","1964-M11","1964-M12","1965","1965-Q1","1965-M01","1965-M02","1965-M03","1965-Q2","1965-M04","1965-M05","1965-M06","1965-Q3","1965-M07","1965-M08","1965-M09","1965-Q4","1965-M10","1965-M11","1965-M12","1966","1966-Q1","1966-M01","1966-M02","1966-M03","1966-Q2","1966-M04","1966-M05","1966-M06","1966-Q3","1966-M07","1966-M08","1966-M09","1966-Q4","1966-M10","1966-M11","1966-M12","1967","1967-Q1","1967-M01","1967-M02","1967-M03","1967-Q2","1967-M04","1967-M05","1967-M06","1967-Q3","1967-M07","1967-M08","1967-M09","1967-Q4","1967-M10","1967-M11","1967-M12","1968","1968-Q1","1968-M01","1968-M02","1968-M03","1968-Q2","1968-M04","1968-M05","1968-M06","1968-Q3","1968-M07","1968-M08","1968-M09","1968-Q4","1968-M10","1968-M11","1968-M12","1969","1969-Q1","1969-M01","1969-M02","1969-M03","1969-Q2","1969-M04","1969-M05","1969-M06","1969-Q3","1969-M07","1969-M08","1969-M09","1969-Q4","1969-M10","1969-M11","1969-M12","1970","1970-Q1","1970-M01","1970-M02","1970-M03","1970-Q2","1970-M04","1970-M05","1970-M06","1970-Q3","1970-M07","1970-M08","1970-M09","1970-Q4","1970-M10","1970-M11","1970-M12","1971","1971-Q1","1971-M01","1971-M02","1971-M03","1971-Q2","1971-M04","1971-M05","1971-M06","1971-Q3","1971-M07","1971-M08","1971-M09","1971-Q4","1971-M10","1971-M11","1971-M12","1972","1972-Q1","1972-M01","1972-M02","1972-M03","1972-Q2","1972-M04","1972-M05","1972-M06","1972-Q3","1972-M07","1972-M08","1972-M09","1972-Q4","1972-M10","1972-M11","1972-M12","1973","1973-Q1","1973-M01","1973-M02","1973-M03","1973-Q2","1973-M04","1973-M05","1973-M06","1973-Q3","1973-M07","1973-M08","1973-M09","1973-Q4","1973-M10","1973-M11","1973-M12","1974","1974-Q1","1974-M01","1974-M02","1974-M03","1974-Q2","1974-M04","1974-M05","1974-M06","1974-Q3","1974-M07","1974-M08","1974-M09","1974-Q4","1974-M10","1974-M11","1974-M12","1975","1975-Q1","1975-M01","1975-M02","1975-M03","1975-Q2","1975-M04","1975-M05","1975-M06","1975-Q3","1975-M07","1975-M08","1975-M09","1975-Q4","1975-M10","1975-M11","1975-M12","1976","1976-Q1","1976-M01","1976-M02","1976-M03","1976-Q2","1976-M04","1976-M05","1976-M06","1976-Q3","1976-M07","1976-M08","1976-M09","1976-Q4","1976-M10","1976-M11","1976-M12","1977","1977-Q1","1977-M01","1977-M02","1977-M03","1977-Q2","1977-M04","1977-M05","1977-M06","1977-Q3","1977-M07","1977-M08","1977-M09","1977-Q4","1977-M10","1977-M11","1977-M12","1978","1978-Q1","1978-M01","1978-M02","1978-M03","1978-Q2","1978-M04","1978-M05","1978-M06","1978-Q3","1978-M07","1978-M08","1978-M09","1978-Q4","1978-M10","1978-M11","1978-M12","1979","1979-Q1","1979-M01","1979-M02","1979-M03","1979-Q2","1979-M04","1979-M05","1979-M06","1979-Q3","1979-M07","1979-M08","1979-M09","1979-Q4","1979-M10","1979-M11","1979-M12","1980","1980-Q1","1980-M01","1980-M02","1980-M03","1980-Q2","1980-M04","1980-M05","1980-M06","1980-Q3","1980-M07","1980-M08","1980-M09","1980-Q4","1980-M10","1980-M11","1980-M12","1981","1981-Q1","1981-M01","1981-M02","1981-M03","1981-Q2","1981-M04","1981-M05","1981-M06","1981-Q3","1981-M07","1981-M08","1981-M09","1981-Q4","1981-M10","1981-M11","1981-M12","1982","1982-Q1","1982-M01","1982-M02","1982-M03","1982-Q2","1982-M04","1982-M05","1982-M06","1982-Q3","1982-M07","1982-M08","1982-M09","1982-Q4","1982-M10","1982-M11","1982-M12","1983","1983-Q1","1983-M01","1983-M02","1983-M03","1983-Q2","1983-M04","1983-M05","1983-M06","1983-Q3","1983-M07","1983-M08","1983-M09","1983-Q4","1983-M10","1983-M11","1983-M12","1984","1984-Q1","1984-M01","1984-M02","1984-M03","1984-Q2","1984-M04","1984-M05","1984-M06","1984-Q3","1984-M07","1984-M08","1984-M09","1984-Q4","1984-M10","1984-M11","1984-M12","1985","1985-Q1","1985-M01","1985-M02","1985-M03","1985-Q2","1985-M04","1985-M05","1985-M06","1985-Q3","1985-M07","1985-M08","1985-M09","1985-Q4","1985-M10","1985-M11","1985-M12","1986","1986-Q1","1986-M01","1986-M02","1986-M03","1986-Q2","1986-M04","1986-M05","1986-M06","1986-Q3","1986-M07","1986-M08","1986-M09","1986-Q4","1986-M10","1986-M11","1986-M12","1987","1987-Q1","1987-M01","1987-M02","1987-M03","1987-Q2","1987-M04","1987-M05","1987-M06","1987-Q3","1987-M07","1987-M08","1987-M09","1987-Q4","1987-M10","1987-M11","1987-M12","1988","1988-Q1","1988-M01","1988-M02","1988-M03","1988-Q2","1988-M04","1988-M05","1988-M06","1988-Q3","1988-M07","1988-M08","1988-M09","1988-Q4","1988-M10","1988-M11","1988-M12","1989","1989-Q1","1989-M01","1989-M02","1989-M03","1989-Q2","1989-M04","1989-M05","1989-M06","1989-Q3","1989-M07","1989-M08","1989-M09","1989-Q4","1989-M10","1989-M11","1989-M12","1990","1990-Q1","1990-M01","1990-M02","1990-M03","1990-Q2","1990-M04","1990-M05","1990-M06","1990-Q3","1990-M07","1990-M08","1990-M09","1990-Q4","1990-M10","1990-M11","1990-M12","1991","1991-Q1","1991-M01","1991-M02","1991-M03","1991-Q2","1991-M04","1991-M05","1991-M06","1991-Q3","1991-M07","1991-M08","1991-M09","1991-Q4","1991-M10","1991-M11","1991-M12","1992","1992-Q1","1992-M01","1992-M02","1992-M03","1992-Q2","1992-M04","1992-M05","1992-M06","1992-Q3","1992-M07","1992-M08","1992-M09","1992-Q4","1992-M10","1992-M11","1992-M12","1993","1993-Q1","1993-M01","1993-M02","1993-M03","1993-Q2","1993-M04","1993-M05","1993-M06","1993-Q3","1993-M07","1993-M08","1993-M09","1993-Q4","1993-M10","1993-M11","1993-M12","1994","1994-Q1","1994-M01","1994-M02","1994-M03","1994-Q2","1994-M04","1994-M05","1994-M06","1994-Q3","1994-M07","1994-M08","1994-M09","1994-Q4","1994-M10","1994-M11","1994-M12","1995","1995-Q1","1995-M01","1995-M02","1995-M03","1995-Q2","1995-M04","1995-M05","1995-M06","1995-Q3","1995-M07","1995-M08","1995-M09","1995-Q4","1995-M10","1995-M11","1995-M12","1996","1996-Q1","1996-M01","1996-M02","1996-M03","1996-Q2","1996-M04","1996-M05","1996-M06","1996-Q3","1996-M07","1996-M08","1996-M09","1996-Q4","1996-M10","1996-M11","1996-M12","1997","1997-Q1","1997-M01","1997-M02","1997-M03","1997-Q2","1997-M04","1997-M05","1997-M06","1997-Q3","1997-M07","1997-M08","1997-M09","1997-Q4","1997-M10","1997-M11","1997-M12","1998","1998-Q1","1998-M01","1998-M02","1998-M03","1998-Q2","1998-M04","1998-M05","1998-M06","1998-Q3","1998-M07","1998-M08","1998-M09","1998-Q4","1998-M10","1998-M11","1998-M12","1999","1999-Q1","1999-M01","1999-M02","1999-M03","1999-Q2","1999-M04","1999-M05","1999-M06","1999-Q3","1999-M07","1999-M08","1999-M09","1999-Q4","1999-M10","1999-M11","1999-M12","2000","2000-Q1","2000-M01","2000-M02","2000-M03","2000-Q2","2000-M04","2000-M05","2000-M06","2000-Q3","2000-M07","2000-M08","2000-M09","2000-Q4","2000-M10","2000-M11","2000-M12","2001","2001-Q1","2001-M01","2001-M02","2001-M03","2001-Q2","2001-M04","2001-M05","2001-M06","2001-Q3","2001-M07","2001-M08","2001-M09","2001-Q4","2001-M10","2001-M11","2001-M12","2002","2002-Q1","2002-M01","2002-M02","2002-M03","2002-Q2","2002-M04","2002-M05","2002-M06","2002-Q3","2002-M07","2002-M08","2002-M09","2002-Q4","2002-M10","2002-M11","2002-M12","2003","2003-Q1","2003-M01","2003-M02","2003-M03","2003-Q2","2003-M04","2003-M05","2003-M06","2003-Q3","2003-M07","2003-M08","2003-M09","2003-Q4","2003-M10","2003-M11","2003-M12","2004","2004-Q1","2004-M01","2004-M02","2004-M03","2004-Q2","2004-M04","2004-M05","2004-M06","2004-Q3","2004-M07","2004-M08","2004-M09","2004-Q4","2004-M10","2004-M11","2004-M12","2005","2005-Q1","2005-M01","2005-M02","2005-M03","2005-Q2","2005-M04","2005-M05","2005-M06","2005-Q3","2005-M07","2005-M08","2005-M09","2005-Q4","2005-M10","2005-M11","2005-M12","2006","2006-Q1","2006-M01","2006-M02","2006-M03","2006-Q2","2006-M04","2006-M05","2006-M06","2006-Q3","2006-M07","2006-M08","2006-M09","2006-Q4","2006-M10","2006-M11","2006-M12","2007","2007-Q1","2007-M01","2007-M02","2007-M03","2007-Q2","2007-M04","2007-M05","2007-M06","2007-Q3","2007-M07","2007-M08","2007-M09","2007-Q4","2007-M10","2007-M11","2007-M12","2008","2008-Q1","2008-M01","2008-M02","2008-M03","2008-Q2","2008-M04","2008-M05","2008-M06","2008-Q3","2008-M07","2008-M08","2008-M09","2008-Q4","2008-M10","2008-M11","2008-M12","2009","2009-Q1","2009-M01","2009-M02","2009-M03","2009-Q2","2009-M04","2009-M05","2009-M06","2009-Q3","2009-M07","2009-M08","2009-M09","2009-Q4","2009-M10","2009-M11","2009-M12","2010","2010-Q1","2010-M01","2010-M02","2010-M03","2010-Q2","2010-M04","2010-M05","2010-M06","2010-Q3","2010-M07","2010-M08","2010-M09","2010-Q4","2010-M10","2010-M11","2010-M12","2011","2011-Q1","2011-M01","2011-M02","2011-M03","2011-Q2","2011-M04","2011-M05","2011-M06","2011-Q3","2011-M07","2011-M08","2011-M09","2011-Q4","2011-M10","2011-M11","2011-M12","2012","2012-Q1","2012-M01","2012-M02","2012-M03","2012-Q2","2012-M04","2012-M05","2012-M06","2012-Q3","2012-M07","2012-M08","2012-M09","2012-Q4","2012-M10","2012-M11","2012-M12","2013","2013-Q1","2013-M01","2013-M02","2013-M03","2013-Q2","2013-M04","2013-M05","2013-M06","2013-Q3","2013-M07","2013-M08","2013-M09","2013-Q4","2013-M10","2013-M11","2013-M12","2014","2014-Q1","2014-M01","2014-M02","2014-M03","2014-Q2","2014-M04","2014-M05","2014-M06","2014-Q3","2014-M07","2014-M08","2014-M09","2014-Q4","2014-M10","2014-M11","2014-M12","2015","2015-Q1","2015-M01","2015-M02","2015-M03","2015-Q2","2015-M04","2015-M05","2015-M06","2015-Q3","2015-M07","2015-M08","2015-M09","2015-Q4","2015-M10","2015-M11","2015-M12","2016","2016-Q1","2016-M01","2016-M02","2016-M03","2016-Q2","2016-M04","2016-M05","2016-M06","2016-Q3","2016-M07","2016-M08","2016-M09","2016-Q4","2016-M10","2016-M11","2016-M12","2017","2017-Q1","2017-M01","2017-M02","2017-M03","2017-Q2","2017-M04","2017-M05","2017-M06","2017-Q3","2017-M07","2017-M08","2017-M09","2017-Q4","2017-M10","2017-M11","2017-M12","2018","2018-Q1","2018-M01","2018-M02","2018-M03","2018-Q2","2018-M04","2018-M05","2018-M06","2018-Q3","2018-M07","2018-M08","2018-M09","2018-Q4","2018-M10","2018-M11","2018-M12","2019","2019-Q1","2019-M01","2019-M02","2019-M03","2019-Q2","2019-M04","2019-M05","2019-M06","2019-Q3","2019-M07","2019-M08","2019-M09","2019-Q4","2019-M10","2019-M11","2019-M12","2020","2020-Q1","2020-M01","2020-M02","2020-M03","2020-Q2","2020-M04","2020-M05","2020-M06","2020-Q3","2020-M07","2020-M08","2020-M09","2020-Q4","2020-M10","2020-M11","2020-M12","2021","2021-Q1","2021-M01","2021-M02","2021-M03","2021-Q2","2021-M04","2021-M05","2021-M06","2021-Q3","2021-M07","2021-M08","2021-M09","2021-Q4","2021-M10","2021-M11","2021-M12","2022","2022-Q1","2022-M01","

In [41]:
df_paises.tail(10)
df_paises.sample(3)
df_paises.iloc[1:5,[1]]
len(df_paises)
df_paises.shape
df_paises.columns
df_paises.dtypes
df_paises.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1669 entries, 0 to 1668
Data columns (total 4 columns):

PUNTO 2

In [11]:
!pip install wbdata

Collecting wbdata
  Downloading wbdata-1.1.0-py3-none-any.whl.metadata (2.1 kB)
Collecting appdirs<2,>=1.4 (from wbdata)
  Downloading appdirs-1.4.4-py2.py3-none-any.whl.metadata (9.0 kB)
Collecting backoff<3,>=2.2.1 (from wbdata)
  Downloading backoff-2.2.1-py3-none-any.whl.metadata (14 kB)
Collecting cachetools<6,>=5.3.2 (from wbdata)
  Downloading cachetools-5.5.2-py3-none-any.whl.metadata (5.4 kB)
Collecting dateparser<2,>=1.2.0 (from wbdata)
  Downloading dateparser-1.3.0-py3-none-any.whl.metadata (30 kB)
Collecting decorator<6,>=5.1.1 (from wbdata)
  Downloading decorator-5.2.1-py3-none-any.whl.metadata (3.9 kB)
Requirement already satisfied: requests<3,>=2.0 in /usr/local/lib/python3.12/dist-packages (from wbdata) (2.32.4)
Collecting shelved-cache<0.4,>=0.3.1 (from wbdata)
  Downloading shelved_cache-0.3.1-py3-none-any.whl.metadata (4.7 kB)
Requirement already satisfied: tabulate<1,>=0.8.5 in /usr/local/lib/python3.12/dist-packages (from wbdata) (0.9.0)
Requirement already satisfied: python-dateutil>=2.7.0 in /usr/local/lib/python3.12/dist-packages (from dateparser<2,>=1.2.0->wbdata) (2.9.0.post0)
Requirement already satisfied: pytz>=2024.2 in /usr/local/lib/python3.12/dist-packages (from dateparser<2,>=1.2.0->wbdata) (2025.2)
Requirement already satisfied: regex>=2024.9.11 in /usr/local/lib/python3.12/dist-packages (from dateparser<2,>=1.2.0->wbdata) (2025.11.3)
Requirement already satisfied: tzlocal>=0.2 in /usr/local/lib/python3.12/dist-packages (from dateparser<2,>=1.2.0->wbdata) (5.3.1)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.0->wbdata) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.0->wbdata) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.0->wbdata) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.0->wbdata) (2026.2.25)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.7.0->dateparser<2,>=1.2.0->wbdata) (1.17.0)
Downloading wbdata-1.1.0-py3-none-any.whl (18 kB)
Downloading appdirs-1.4.4-py2.py3-none-any.whl (9.6 kB)
Downloading backoff-2.2.1-py3-none-any.whl (15 kB)
Downloading cachetools-5.5.2-py3-none-any.whl (10 kB)
Downloading dateparser-1.3.0-py3-none-any.whl (318 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 318.7/318.7 kB 8.7 MB/s eta 0:00:00
Downloading decorator-5.2.1-py3-none-any.whl (9.2 kB)
Downloading shelved_cache-0.3.1-py3-none-any.whl (7.8 kB)
Installing collected packages: appdirs, decorator, cachetools, backoff, shelved-cache, dateparser, wbdata
  Attempting uninstall: decorator
    Found existing installation: decorator 4.4.2
    Uninstalling decorator-4.4.2:
      Successfully uninstalled decorator-4.4.2
  Attempting uninstall: cachetools
    Found existing installation: cachetools 6.2.6
    Uninstalling cachetools-6.2.6:
      Successfully uninstalled cachetools-6.2.6
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
ipython 7.34.0 requires jedi>=0.16, which is not installed.
moviepy 1.0.3 requires decorator<5.0,>=4.0.2, but you have decorator 5.2.1 which is incompatible.
Successfully installed appdirs-1.4.4 backoff-2.2.1 cachetools-5.5.2 dateparser-1.3.0 decorator-5.2.1 shelved-cache-0.3.1 wbdata-1.1.0

In [4]:
import wbdata
import datetime

In [8]:
paises = "COL;BRA;MEX;CHL;ECU;PER"
indicador = {"FP.CPI.TOTL.ZG": "Inflación anual"}
fecha_inicio = datetime.datetime(2010, 1, 1)
fecha_final = datetime.datetime(2023, 1, 1)
df = wbdata.get_dataframe(indicador, country = paises, date=(fecha_inicio, fecha_final))
df

              Inflación anual
country date
Brazil  2023             4.59
        2022             9.28
        2021             8.30
        2020             3.21
        2019             3.73
...                       ...
Peru    2014             3.41
        2013             2.77
        2012             3.61
        2011             3.37
        2010             1.53

[84 rows x 1 columns]

In [39]:
df.tail(10)
df.sample(3)
df.iloc[1:5,[1]]
len(df)
df.shape
df.columns
df.dtypes
df.info()

<class 'wbdata.client.DataFrame'>
Index: 14 entries, 2023 to 2010
Data columns (total 5 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Crecimiento PIB     14 non-null     float64
 1   PIB per capita PPA  14 non-null     float64
 2   Inflacion           14 non-null     float64
 3   Desempleo           14 non-null     float64
 4   Poblacion           14 non-null     float64
dtypes: float64(5)
memory usage: 672.0+ bytes

PUNTO 3

In [9]:
indicador = {
"NY.GDP.MKTP.KD.ZG": "Crecimiento PIB",
"NY.GDP.PCAP.PP.CD": "PIB per capita PPA",
"FP.CPI.TOTL.ZG": "Inflacion",
"SL.UEM.TOTL.ZS": "Desempleo",
"SP.POP.TOTL": "Poblacion"
}

fecha_inicio = datetime.datetime(2010, 1, 1)
fecha_final = datetime.datetime(2023, 1, 1)

df = wbdata.get_dataframe(indicador, country="DEU", date=(fecha_inicio, fecha_final))

df

      Crecimiento PIB  PIB per capita PPA  Inflacion  Desempleo     Poblacion
date
2023            -0.87           71,684.03       5.95       3.07 83,287,273.00
2022             1.81           69,048.99       6.87       3.14 83,177,813.00
2021             3.91           62,530.77       3.07       3.59 83,196,078.00
2020            -4.13           58,685.87       0.14       3.88 83,160,871.00
2019             0.98           59,270.73       1.45       3.16 83,092,962.00
2018             1.14           56,273.04       1.73       3.38 82,905,782.00
2017             2.80           54,110.25       1.51       3.78 82,657,002.00
2016             2.22           51,569.90       0.49       4.10 82,348,669.00
2015             1.66           48,545.40       0.51       4.61 81,686,611.00
2014             2.18           47,938.80       0.91       4.98 80,982,500.00
2013             0.40           45,889.02       1.50       5.32 80,645,605.00
2012             0.46           44,229.39       2.01       5.37 80,425,823.00
2011             3.76           43,398.34       2.08       5.97 80,274,983.00
2010             4.13           39,726.10       1.10       7.04 81,776,930.00

In [40]:
df.tail(10)
df.sample(3)
df.iloc[1:5,[1]]
len(df)
df.shape
df.columns
df.dtypes
df.info()

<class 'wbdata.client.DataFrame'>
Index: 14 entries, 2023 to 2010
Data columns (total 5 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Crecimiento PIB     14 non-null     float64
 1   PIB per capita PPA  14 non-null     float64
 2   Inflacion           14 non-null     float64
 3   Desempleo           14 non-null     float64
 4   Poblacion           14 non-null     float64
dtypes: float64(5)
memory usage: 672.0+ bytes

PUNTO 4

In [10]:
import requests

Punto A

In [11]:
url = "https://www.datos.gov.co/resource/gdxc-w37w.json"

# Solicitud de API
response = requests.get(url)
data = response.json()

# Convertir a DataFrame
df_municipios = pd.DataFrame(data)

df_municipios.head()

,cod_dpto,dpto,cod_mpio,nom_mpio,tipo_municipio,longitud,latitud
0,05,ANTIOQUIA,05001,MEDELLÍN,Municipio,"-75,581775","6,246631"
1,05,ANTIOQUIA,05002,ABEJORRAL,Municipio,"-75,428739","5,789315"
2,05,ANTIOQUIA,05004,ABRIAQUÍ,Municipio,"-76,064304","6,632282"
3,05,ANTIOQUIA,05021,ALEJANDRÍA,Municipio,"-75,141346","6,376061"
4,05,ANTIOQUIA,05030,AMAGÁ,Municipio,"-75,702188","6,038708"

In [12]:
df_municipios.head()

df_municipios.tail(10)

df_municipios.sample(3)

df_municipios.iloc[1:5,[1]]

len(df_municipios)

df_municipios.shape

df_municipios.columns

df_municipios.dtypes

df_municipios.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   cod_dpto        1000 non-null   object
 1   dpto            1000 non-null   object
 2   cod_mpio        1000 non-null   object
 3   nom_mpio        1000 non-null   object
 4   tipo_municipio  1000 non-null   object
 5   longitud        1000 non-null   object
 6   latitud         1000 non-null   object
dtypes: object(7)
memory usage: 54.8+ KB

Punto B

In [13]:
url = "https://www.datos.gov.co/resource/3vbk-w3sc.json"

# Solicitud de API
response = requests.get(url)
data = response.json()

# Convertir a DataFrame
df_ciiu = pd.DataFrame(data)

df_ciiu.head()

,clasificacion_ciiu,agencia,empresas_asociativas_de,empresas_de_economia_solidaria,empresas_unipersonales,entidades_sin_animo_de_lucro,establecimientos,personas_naturales,sociedad_anonima,sociedad_limitada,sociedad_por_acciones,sociedades_en_comandita_simple,sucursal
0,A0112 ** Cultivo de arroz,0,0,0,0,0,0,1,0,0,0,0,0
1,A0113 ** Cultivo de hortalizas raices y tuber...,0,0,0,0,8,2,2,0,0,0,0,0
2,A0119 ** Otros cultivos transitorios n.c.p.,0,0,0,0,0,0,0,0,1,0,0,0
3,A0121 ** Cultivo de frutas tropicales y subtro...,0,0,0,0,5,1,3,0,0,1,0,0
4,A0123 ** Cultivo de cafe,0,0,0,0,7,1,0,0,0,0,0,0

In [14]:
df_ciiu.head()

df_ciiu.tail(10)

df_ciiu.sample(3)

df_ciiu.iloc[1:5,[1]]

len(df_ciiu)

df_ciiu.shape

df_ciiu.columns

df_ciiu.dtypes

df_ciiu.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 329 entries, 0 to 328
Data columns (total 13 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   clasificacion_ciiu              329 non-null    object
 1   agencia                         329 non-null    object
 2   empresas_asociativas_de         329 non-null    object
 3   empresas_de_economia_solidaria  329 non-null    object
 4   empresas_unipersonales          329 non-null    object
 5   entidades_sin_animo_de_lucro    329 non-null    object
 6   establecimientos                329 non-null    object
 7   personas_naturales              329 non-null    object
 8   sociedad_anonima                329 non-null    object
 9   sociedad_limitada               329 non-null    object
 10  sociedad_por_acciones           329 non-null    object
 11  sociedades_en_comandita_simple  329 non-null    object
 12  sucursal                        329 non-null    object
dtypes: object(13)
memory usage: 33.5+ KB

PUNTO 5

In [15]:
!pip install fredapi

Collecting fredapi
  Downloading fredapi-0.5.2-py3-none-any.whl.metadata (5.0 kB)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (from fredapi) (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas->fredapi) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas->fredapi) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas->fredapi) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas->fredapi) (2025.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas->fredapi) (1.17.0)
Downloading fredapi-0.5.2-py3-none-any.whl (11 kB)
Installing collected packages: fredapi
Successfully installed fredapi-0.5.2

In [24]:
import requests
import pandas as pd

url = "https://api.open-meteo.com/v1/forecast?latitude=4.6097&longitude=-74.0817&hourly=temperature_2m"

# Solicitud a la API
response = requests.get(url)
data = response.json()

# Convertir a DataFrame
df_clima = pd.DataFrame(data["hourly"])

df_clima.head()

               time  temperature_2m
0  2026-03-06T00:00           15.30
1  2026-03-06T01:00           14.80
2  2026-03-06T02:00           14.30
3  2026-03-06T03:00           13.80
4  2026-03-06T04:00           13.40

In [25]:
df_clima.tail(10)
df_clima.sample(3)
df_clima.iloc[1:5,[1]]
len(df_clima)
df_clima.shape
df_clima.columns
df_clima.dtypes
df_clima.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 168 entries, 0 to 167
Data columns (total 2 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   time            168 non-null    object
 1   temperature_2m  168 non-null    float64
dtypes: float64(1), object(1)
memory usage: 2.8+ KB